name = "iceberg-light"
background = "light"

[hues]
hue_base = 230

hue_red    = 340
hue_orange = 25
hue_green  = 90
hue_cyan   = 200
hue_blue   = 220
hue_purple = 260
hue_pale   = 235

[colors]
# palette
blue   = "hsl($hue_blue, 0.55, 0.40)"
green  = "hsl($hue_green, 0.40, 0.40)"
cyan   = "hsl($hue_cyan, 0.45, 0.45)"
orange = "hsl($hue_orange, 0.55, 0.50)"
purple = "hsl($hue_purple, 0.38, 0.53)"
red    = "hsl($hue_red, 0.55, 0.56)"
pale   = "hsl($hue_pale, 0.30, 0.45)"

# normal
normal_bg = "hsl($hue_base, 0.10, 0.92)"
normal_fg = "hsl($hue_base, 0.20, 0.25)"

# tint
blue_tint_bg   = "mix(blue, normal_bg, 0.15)"
blue_tint_fg   = "mix(blue, normal_fg, 0.40)"
green_tint_bg  = "mix(green, normal_bg, 0.15)"
green_tint_fg  = "mix(green, normal_fg, 0.40)"
cyan_tint_bg   = "mix(cyan, normal_bg, 0.15)"
cyan_tint_fg   = "mix(cyan, normal_fg, 0.40)"
purple_tint_bg = "mix(purple, normal_bg, 0.15)"
purple_tint_fg = "mix(purple, normal_fg, 0.40)"
red_tint_bg    = "mix(red, normal_bg, 0.15)"
red_tint_fg    = "mix(red, normal_fg, 0.40)"

# linenr
linenr_bg       = "adjust(normal_bg, 0.10, -0.03)"
linenr_fg       = "darken(linenr_bg, 0.20)"
cursorlinenr_bg = "adjust(linenr_bg, 0.05, -0.05)"
cursorlinenr_fg = "adjust(linenr_fg, 0.10, -0.20)"

# diff
difftext_bg = "mix(cyan, normal_bg, 0.35)"
difftext_fg = "normal_fg"

# statusline
statusline_bg   = "hsl($hue_base, 0.20, 0.55)"
statusline_fg   = "normal_bg"
statuslinenc_bg = "cursorlinenr_bg"
statuslinenc_fg = "darken(statuslinenc_bg, 0.20)"

# pmenu
pmenu_bg    = "cursorlinenr_bg"
pmenu_fg    = "normal_fg"
pmenusel_bg = "adjust(pmenu_bg, 0.05, -0.10)"
pmenusel_fg = "normal_fg"

# misc
comment_fg    = "hsl($hue_base, 0.15, 0.58)"
cursorline_bg = "linenr_bg"
folded_bg     = "linenr_bg"
folded_fg     = "adjust(folded_bg, -0.05, -0.35)"
matchparen_bg = "darken(normal_bg, 0.15)"
matchparen_fg = "darken(normal_fg, 0.00)"
search_bg     = "hsl($hue_orange, 0.60, 0.80)"
search_fg     = "hsl($hue_orange, 0.50, 0.35)"
specialkey_fg = "adjust(normal_bg, 0.25, -0.18)"
tablinesel_bg = "normal_bg"
tablinesel_fg = "mix(normal_fg, normal_bg, 0.75)"
todo_bg       = "green_tint_bg"
todo_fg       = "green"
visual_bg     = "adjust(normal_bg, 0.05, -0.10)"
whitespace_fg = "adjust(normal_bg, 0.08, -0.09)"
wildmenu_bg   = "darken(statusline_bg, 0.30)"
wildmenu_fg   = "statusline_fg"

search_alt_1_bg = "hsl($hue_green, 0.32, 0.65)" 
search_alt_1_fg = "hsl($hue_green, 0.50, 0.15)" 
search_alt_2_bg = "hsl($hue_purple, 0.32, 0.70)" 
search_alt_2_fg = "hsl($hue_purple, 0.50, 0.15)" 

[highlights]
Normal           = "normal_fg normal_bg"
ColorColumn      = "- cursorline_bg"
CursorColumn     = "- cursorline_bg"
CursorLine       = "- cursorline_bg"
Comment          = "comment_fg"
Conceal          = "comment_fg normal_bg "
Constant         = "purple"
Cursor           = "normal_bg normal_fg"
CursorLineNr     = "cursorlinenr_fg cursorlinenr_bg"
Delimiter        = "normal_fg"
DiffAdd          = "green_tint_fg green_tint_bg"
DiffChange       = "cyan_tint_fg cyan_tint_bg"
DiffDelete       = "red_tint_fg red_tint_bg"
DiffText         = "difftext_fg difftext_bg"
Directory        = "blue"
Error            = "red normal_bg"
ErrorMsg         = "red normal_bg"
WarningMsg       = "red normal_bg"
EndOfBuffer      = "whitespace_fg"
NonText          = "whitespace_fg"
Whitespace       = "whitespace_fg"
Folded           = "folded_fg folded_bg"
FoldColumn       = "linenr_fg linenr_bg"
Function         = "blue"
Identifier       = "blue"
Ignore           = "- -"
Include          = "blue"
IncSearch        = "- - r"
LineNr           = "linenr_fg linenr_bg"
MatchParen       = "matchparen_fg matchparen_bg"
ModeMsg          = "comment_fg"
MoreMsg          = "green"
Operator         = "blue"
Pmenu            = "pmenu_fg pmenu_bg"
PmenuSbar        = "- pmenu_bg"
PmenuSel         = "pmenusel_fg pmenusel_bg"
PmenuThumb       = "- pmenu_fg"
PreProc          = "green"
Question         = "green"
QuickFixLine     = "normal_fg visual_bg"
Search           = "search_fg search_bg"
SignColumn       = "linenr_fg linenr_bg"
Special          = "green"
SpecialKey       = "specialkey_fg"
SpellBad         = "- - c red"
SpellCap         = "- - c blue"
SpellLocal       = "- - c cyan"
SpellRare        = "- - c purple"
Statement        = "blue"
StatusLine       = "statusline_bg statusline_fg r"
StatusLineTerm   = "statusline_bg statusline_fg r"
StatusLineNC     = "statuslinenc_bg statuslinenc_fg r"
StatusLineTermNC = "statuslinenc_bg statuslinenc_fg r"
StorageClass     = "blue"
String           = "cyan"
Structure        = "blue"
TabLine          = "statuslinenc_fg statuslinenc_bg"
TabLineFill      = "statuslinenc_bg statuslinenc_fg"
TabLineSel       = "tablinesel_fg tablinesel_bg"
TermCursorNC     = "normal_bg comment_fg"
Title            = "orange"
Todo             = "todo_fg todo_bg"
Type             = "blue"
Underlined       = "blue - u"
VertSplit        = "statuslinenc_bg statuslinenc_bg"
WinSeparator     = "statuslinenc_bg statuslinenc_bg"
Visual           = "- visual_bg"
VisualNOS        = "- visual_bg"
WildMenu         = "wildmenu_fg wildmenu_bg"

icebergNormalFg = "normal_fg"

diffAdded   = "green"
diffRemoved = "red"

GitGutterAdd          = "green linenr_bg"
GitGutterChange       = "cyan linenr_bg"
GitGutterChangeDelete = "cyan linenr_bg"
GitGutterDelete       = "red linenr_bg"

DiagnosticUnderlineInfo  = "- - u cyan"
DiagnosticUnderlineHint  = "- - u comment_fg"
DiagnosticUnderlineWarn  = "- - u orange"
DiagnosticUnderlineError = "- - u red"

DiagnosticInfo  = "cyan"
DiagnosticHint  = "comment_fg"
DiagnosticWarn  = "orange"
DiagnosticError = "red"

DiagnosticSignInfo  = "cyan linenr_bg"
DiagnosticSignHint  = "comment_fg linenr_bg"
DiagnosticSignWarn  = "orange linenr_bg"
DiagnosticSignError = "red linenr_bg"

DiagnosticFloatingHint = "pmenu_fg pmenu_bg"

# additions
NormalFloat = "normal_fg pmenu_bg"
FloatBorder = "comment_fg pmenu_bg"
FloatTitle  = "orange"

Method = "pale"
Uri    = "cyan - u"

CmpItemAbbr              = "link:icebergNormalFg"
CmpItemAbbrDeprecated    = "comment_fg"
CmpItemAbbrMatch         = "orange"
CmpItemAbbrMatchFuzzy    = "green"
CmpItemKind              = "blue"
CmpItemKindClass         = "link:Type"
CmpItemKindColor         = "link:Special"
CmpItemKindConstant      = "link:Constant"
CmpItemKindConstructor   = "link:icebergNormalFg"
CmpItemKindEnum          = "link:Type"
CmpItemKindEnumMember    = "link:Constant"
CmpItemKindEvent         = "link:Special"
CmpItemKindField         = "link:icebergNormalFg"
CmpItemKindFile          = "link:icebergNormalFg"
CmpItemKindFolder        = "link:Directory"
CmpItemKindFunction      = "link:Method"
CmpItemKindInterface     = "link:Type"
CmpItemKindKeyword       = "link:Statement"
CmpItemKindMethod        = "link:Method"
CmpItemKindModule        = "link:Type"
CmpItemKindOperator      = "link:icebergNormalFg"
CmpItemKindProperty      = "link:icebergNormalFg"
CmpItemKindReference     = "link:icebergNormalFg"
CmpItemKindSnippet       = "link:String"
CmpItemKindStruct        = "link:StorageClass"
CmpItemKindText          = "link:String"
CmpItemKindTypeParameter = "link:icebergNormalFg"
CmpItemKindUnit          = "link:Constant"
CmpItemKindValue         = "link:icebergNormalFg"
CmpItemKindVariable      = "link:icebergNormalFg"
CmpItemMenu              = "link:icebergNormalFg"

TelescopeBorder         = "comment_fg"
TelescopeMatching       = "orange"
TelescopePreviewExecute = "green"
TelescopePreviewRead    = "orange"
TelescopePreviewSize    = "green"
TelescopePreviewUser    = "orange"
TelescopePreviewWrite   = "red"
TelescopePromptPrefix   = "green"
TelescopePromptCounter  = "linenr_fg"

NvimTreeFolderIcon   = "link:Directory"
NvimTreeIndentMarker = "link:Directory"
NvimTreeWindowPicker = "search_fg search_bg b"
NvimTreeRootFolder   = "link:Constant"
NvimTreeSpecialFile  = "link:Title"
NvimTreeExecFile     = "link:Special"
NvimTreeDeletedIcon  = "red"
NvimTreeGitMergeIcon = "orange"
NvimTreeGitDirtyIcon = "red"

GitSignsCurrentLineBlame = "linenr_fg"

LeapMatch          = "search_fg search_bg b"
LeapLabelPrimary   = "search_alt_1_fg search_alt_1_bg b"
LeapLabelSecondary = "search_alt_2_fg search_alt_2_bg b"

IblWhitespace = "link:NonText"
IblScope      = "linenr_fg"

TermCursor    = "link:Cursor"
ToolbarButton = "link:TabLineSel"
ToolbarLine   = "link:TabLineFill"

# treesitter
"@attribute"             = "link:Special"
"@boolean"               = "link:Constant"
"@character"             = "link:Constant"
"@character.special"     = "link:Constant"
"@comment"               = "link:Comment"
"@comment.todo.comment"  = "link:Todo"
"@conditional"           = "link:Statement"
"@constant.builtin"      = "link:Constant"
"@constant"              = "link:Constant"
"@constant.macro"        = "link:Constant"
"@constructor"           = "link:icebergNormalFg"
"@error"                 = "link:Error"
"@exception"             = "link:Statement"
"@field"                 = "link:icebergNormalFg"
"@float"                 = "link:Constant"
"@function.builtin"      = "link:Method"
"@function"              = "link:Method"
"@function.macro"        = "link:PreProc"
"@include"               = "link:Method"
"@keyword.function"      = "link:Function"
"@keyword.import"        = "link:Method"
"@keyword"               = "link:Statement"
"@label"                 = "link:Special"
"@method"                = "link:Method"
"@namespace"             = "link:Statement"
"@number"                = "link:Constant"
"@operator"              = "link:icebergNormalFg"
"@parameter"             = "link:icebergNormalFg"
"@preproc"               = "link:PreProc"
"@property"              = "link:icebergNormalFg"
"@punctuation.bracket"   = "link:icebergNormalFg"
"@punctuation.delimiter" = "link:icebergNormalFg"
"@punctuation.special"   = "link:Special"
"@repeat"                = "link:Statement"
"@string.escape"         = "link:Special"
"@string"                = "link:String"
"@string.regex"          = "link:String"
"@string.special"        = "link:Special"
"@tag.attribute"         = "link:Constant"
"@tag.delimiter"         = "link:Statement"
"@tag"                   = "link:Statement"
"@text"                  = "link:icebergNormalFg"
"@text.title"            = "link:Title"
"@text.uri"              = "link:Uri"
"@text.warning"          = "link:Todo"
"@type.builtin"          = "link:Type"
"@type"                  = "link:Type"
"@type.definition"       = "link:Keyword"
"@type.qualifier"        = "link:Keyword"
"@variable.builtin"      = "link:Statement"
"@variable"              = "link:icebergNormalFg"

# language specific highlights
"@property.yaml" = "link:Statement"
"@property.json" = "link:Statement"
"@property.toml" = "link:Statement"

markdownH1Delimiter   = "link:Special"
markdownH2Delimiter   = "link:Special"
markdownH3Delimiter   = "link:Special"
markdownH4Delimiter   = "link:Special"
markdownH5Delimiter   = "link:Special"
markdownCodeDelimiter = "link:Special"
markdownCode          = "link:String"

# lsp semantic highlighting
"@lsp.type.decorator" = "link:Special"
"@lsp.type.function"  = "link:@function"
"@lsp.type.method"    = "link:@method"
"@lsp.type.parameter" = "link:@parameter"
"@lsp.type.property"  = "link:@property"
"@lsp.type.variable"  = "link:icebergNormalFg"

# non treesitter highlights
xmlAttrib      = "link:Constant"
xmlAttribPunct = "link:Statement"
xmlEndTag      = "link:Statement"
xmlNamespace   = "link:Statement"
xmlTag         = "link:Statement"
xmlTagName     = "link:Statement"

[globals]
terminal_color_0          = "cursorline_bg"
terminal_color_1          = "red"
terminal_color_2          = "green"
terminal_color_3          = "orange"
terminal_color_4          = "blue"
terminal_color_5          = "purple"
terminal_color_6          = "cyan"
terminal_color_7          = "normal_fg"
terminal_color_8          = "comment_fg"
terminal_color_9          = "adjust(red, 0.05, -0.05)"
terminal_color_10         = "adjust(green, 0.05, -0.05)"
terminal_color_11         = "adjust(orange, 0.05, -0.05)"
terminal_color_12         = "adjust(blue, 0.05, -0.05)"
terminal_color_13         = "adjust(purple, 0.05, -0.05)"
terminal_color_14         = "adjust(cyan, 0.05, -0.05)"
terminal_color_15         = "adjust(normal_fg, 0.05, -0.05)"
terminal_color_background = "normal_bg"
terminal_color_foreground = "normal_fg"
